<template>
		<div id="container">
			<h2>Cognitive Flexibility Task</h2>

			<p>			Before you continue the expeirment, please fill in the information below. This is vital for data collecting purpose. </p>

			
			<form>
				<input v-model="experimentId" type="text" placeholder="Experiment ID: " disabled>  </input>
				<input v-model="name" type="text" placeholder="Name"> </input>	
				<input v-model="email" type="text" placeholder="Email">  </input>
				<input v-model="age" type="number" placeholder="Age"> </input>
				<br>
				<button v-on:click="storeForm()">Submit </button>
				<div class="error">{{errorMessage}}</div>
			</form>
		</div>
	</div>
</template>

<script>

export default {
		name: 'SignIn',
		data () {
			return {
					email:'',
					experimentId: '', 
					age: 0, 
					name: '', 
					errorMessage: '' 
			}
		},
		methods: {

			// Store data when user click submit and push on firebase 
			storeForm(){
				if (!this.name || !this.email || !this.age){
					this.errorMessage = 'Please fill out all missing information on the form'; 
				} else {
					var userRef = firebase.database().ref('users/'); 
					var newUsersInfo = userRef.push({
						email: this.email, 
						experimentId: 1, 
						name: this.name, 
						age: this.age 
					});

					// Get the unique ID generated by push() by accessing its key
var postID = newUsersInfo.key;
console.log("postID", postID); 



				}

			}
		
		},

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
   #container{
			padding: 2em; 
			height: 30em;
			background: white; 
			border-radius: 4px; 
			margin-left: 20em; 
			margin-right: 20em; 
			margin-top: 5.5em; 
			box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
			color: #283747;
		}
		
		input{
			height: 3em;
			display: block; 
			width: 30em;
			margin-bottom: 1em;
			margin: auto;
			border: 0px; 
			border-bottom: 1px #E5E7E9  solid; 
		}

</style>
